Fix initialization of BgpAttr with Python 3
With Python 3, setting an attribute which is not mentioned in __slots__
fails:

      File "/home/bernat/code/debian/mrtparse/mrtparse/__init__.py", line 1192, in __init__
        self.larg_comm = None
    AttributeError: 'BgpAttr' object has no attribute 'larg_comm'

Fix the type "larg_comm" vs "large_comm".